# Generated by Django 6.0.1 on 2026-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('جديدة', 'جديدة'), ('قيد المعالجة', 'قيد المعالجة'), ('تم الحل', 'تم الحل'), ('مرفوضة', 'مرفوضة')], default='جديدة', max_length=20, verbose_name='حالة الشكوى'),
        ),
    ]
